config/routes.rb
Rails.application.routes.draw do

  #api
  namespace :api do
    namespace :v1 do
      resources :contacts, only: [:index, :create, :show, :update]
      resources :contact_properties, only: [:index, :create, :show, :update]
      resources :submissions, only: [:index, :create, :show, :update]
      resources :reminders, only: [:index, :create, :show, :update]

      post 'hooks', to: 'hooks#subscribe', as: :hook_subscribe
      delete 'hooks', to: 'hooks#unsubscribe', as: :hook_unsubscribe

    end
  end

  resources :email_templates
  resources :contact_properties
  resources :reminders
  resources :notes
  get 'contacts/batch', to: 'contacts#batch', as: :contacts_batch
  post 'contacts/batch', to: 'contacts#batch_create', as: :contacts_batch_create
  get 'contacts/new_email', to: 'contacts#new_email', as: :contact_new_email
  get 'contacts/draft_list_email', to: 'contacts#draft_list_email', as: :draft_list_email
  post 'contacts/new_email_with_list', to: 'contacts#new_email_with_list', as: :post_contact_new_email
  post 'contact_email', to: 'contacts#send_email', as: :contact_email
  post 'filter_contacts', to: 'contacts#filter', as: :filter_contacts

  resources :submissions
  # get 'submissions', to: 'submissions#index', as: :submissions

  resources :contacts

  get 'transactions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :people,
    path: '',
    path_names:
    {
      sign_up: 'register',
    },
    controllers: {
      registrations: 'people/registrations',
      omniauth_callbacks: "people/omniauth_callbacks"
    }

  resources :invites
  get 'invites/:id/resend', to: 'invites#resend', as: :resend_invite

  resources :profiles
  get 'profiles/:id/leave', to: 'profiles#leave', as: :leave_team
  get 'profiles/:id/account', to: 'profiles#account', as: :account
  post 'profiles/:id/toggle', to: 'profiles#toggle', as: :toggle


  get 'admins/new', to: 'admins#new', as: :new_admin
  post 'admins', to: 'admins#create', as: :create_admin

  resources :orgs
  # resources :orgs, :path => ''
  # # resources :orgs, :path => '', :only => [] do
  # #   resources :projects, :path => '', :except => [:index]
  # # end


  resources :transactions, only: [:new, :create]

  post 'connect_subscribe', to: 'transactions#connect_subscribe', as: :connect_payment
  post 'update_subscription', to: 'transactions#update_subscription', as: :update_subscription

  get 'inbox', to: 'inbox#all', as: :inbox


  post "/webhooks", to: 'webhooks#recieve'

  get '/onboarding', to: 'relate_onboarding#profile'
  put '/onboarding', to: 'relate_onboarding#update_profile'

  resources :onboarding


  get '/tos', to: 'marketing#tos'

  get '/', to: 'marketing#relate', as: :home
  get "/", to: 'marketing#relate', as: :onside_home
  root to: 'marketing#relate'


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_person!, :set_person
  before_action :active_org, :set_current_person_tasks, :set_unassigned_tasks, :set_new_submissions, :get_due_tasks

  layout :set_layout

  def show
    @team = @person.teams.first
  end

  def leave
    @team = Team.friendly.find(params[:team])
    @person.leave_team(@team)

    redirect_to team_path(@team)
  end

  def edit
    @profile = Person.find(params[:id])
  end

  def account
    @profile = Person.find(params[:id])
    @plan = @profile.plan_id_from_stripe
  end

  def toggle
    @person = Person.find(params[:id])

    puts params.inspect

    if @person.update_attributes(params[:property].to_sym => params[:value])

    else
      # ... update failed
    end
  end

  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to edit_profile_path(@person), notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: edit_profile_path(@person) }
        format.js {}
      else
        format.html { render :edit }
        format.json { render json: edit_profile_path(@person).errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(
        :invitation_token,
        :team,
        :email,
        :avatar,
        :first_name,
        :last_name,
        :password,
        :password_confirmation,
        :date_of_birth,
        :street_address,
        :locality,
        :region,
        :postal_code
      )
    end

end

app/views/profiles/_payment_details.html.erb
<div class="card">
  <div class="card-content">
    <span class="card-title">Team Treasurer</span>
    <!-- <h6>
      In order to collect online payments for this season we need some
       information from the person who will be responsible
        for collecting the money and paying the league.
    </h6> -->

    <hr class="faint">
    <div class="section-block">
      <div class="treasurer-line">
        <span class="person">
          <img class="circle avatar" src="<%= person.avatar %>">
          <span class="name"><%= person.first_name %></span>
          <span class="name"><%= person.last_name %></span>
        </span>
        <span>
          <span class="card-ending">Card Ending &#8226;&#8226;&#8226;&#8226;</span>
            <%= person.last_four %>
        </span>
      </div>
    </div>
  </div>
  <div class="card-action edit-profile-actions">
    <a class="waves-effect waves-light btn modal-trigger" href="#payment-details-modal">Edit Treasurer</a>
  </div>
</div>

app/views/profiles/account.html.erb
<div class="container">

    <div class="col s12 m8 l8">
      <div class="card">
        <div class="row">
          <div class="col s12">
            <ul class="tabs">
              <% if @person == @active_org.primary_admin %>
                <li class="tab col s3"><a class="active" href="#profile">Profile</a></li>
                <li class="tab col s3"><a href="#org">Team</a></li>
                <li class="tab col s3"><a href="#users">Coaches</a></li>
                <li class="tab col s3"><a href="#billing">Billing</a></li>
              <% else %>
              <li class="tab col s4"><a class="active" href="#profile">Profile</a></li>
              <li class="tab col s4"><a href="#org">Team</a></li>
              <li class="tab col s4"><a href="#users">Coaches</a></li>
              <% end %>
            </ul>
          </div>
          <div id="profile" class="col s12">
              <%= form_for(@person, url: profile_path, method: :put) do |f| %>
                <div class="card-content">
                    <%= f.label :avatar  do %>
                      <% if @person.avatar.length > 1 then %>
                        <div class="profile-avatar">
                          <div class="section__circle--big large-avatar editable">
                              <img id="avatar" src="<%= @person.avatar %>">
                              <div class="change-label">Change</div>
                          </div>
                        </div>
                      <% else %>
                        <div class="profile-avatar">
                          <div class="section__circle--big large-avatar editable">
                              <%= image_tag "anonymous_material.png", id: "avatar" %>
                              <div class="change-label">Change</div>
                          </div>
                        </div>
                      <% end %>
                    <% end %>
                    <%= f.file_field :avatar, style: "display: none;", class: 'photo_upload', onchange: "loadFile(event)" %>

                    <!-- <div class="container"> -->

                      <div class="row">
                        <div class="input-field col s12">
                          <%= f.text_field :first_name, class: "mdl-textfield__input" %>
                          <%= f.label :first_name, class: "mdl-textfield__label" %>
                        </div>
                      </div>

                      <div class="row">
                        <div class="input-field col s12">
                          <%= f.text_field :last_name, class: "mdl-textfield__input" %>
                          <%= f.label :last_name, class: "mdl-textfield__label" %>
                        </div>
                      </div>

                      <div class="row">
                        <div class="input-field col s12">
                          <%= f.email_field :email, class: "mdl-textfield__input" %>
                          <%= f.label :email, class: "mdl-textfield__label" %>
                        </div>
                      </div>

                    <!-- </div> -->
                  </div>
                  <div class="edit-profile-actions card-action">
                    <%= button_tag(type: 'submit', class: "btn waves-effect waves-light") do %>
                      Save
                    <% end %>
                  </div>

                  <div class="card-content">

                    <div class="card blue-grey darken-1">
                      <div class="card-content white-text">
                        <div class="card-title">
                          API Token
                        </div>
                        <p>
                          You can use this to setup integrations with hundreds of applications via <a href="https://zapier.com" style="color: white; text-decoration:underline;">Zapier</a>.
                        </p>

                        <blockquote style="background: rgba(0,0,0,0.28); padding: 1.2rem;">
                          <%= @person.authentication_token %>
                        </blockquote>

                      </div>
                    </div>
                  </div>


              <% end %>

          </div>
          <div id="org" class="col s12">
            <%= render 'orgs/form', org: @active_org %>
          </div>
          <div id="users" class="col s12">
            <%= render 'orgs/admins_list', org: @active_org %>
          </div>
          <% if @person == @active_org.primary_admin %>
            <div id="billing" class="col s12">
              <%= form_tag update_subscription_path, id: "payment-form" do %>
                <div class="card-content">
                  <p class="debit-explanation">
                    Plan
                  </p>

                  <div id="pricing-frequency" class="switch" style="margin-bottom: 20px;">
                    <label>
                      Pay Monthly
                      <%= check_box_tag :pricing_frequency%>
                      <span class="lever"></span>
                      Pay Annually
                    </label>
                  </div>

                  <div id="monthly-pricing">
                    <p>
                      <input class="with-gap" name="group1" type="radio" id="connect-basic-monthly" value="connect-basic-monthly"/>
                      <label for="connect-basic-monthly">$30/mth Individual Plan(1 user)</label>
                    </p>
                    <p>
                      <input class="with-gap" name="group1" type="radio" id="connect-team-monthly" value="connect-team-monthly"/>
                      <label for="connect-team-monthly">$50/mth Team Plan(5 users)</label>
                    </p>
                    <p>
                      <input class="with-gap" name="group1" type="radio" id="connect-business-monthly" value="connect-business-monthly"/>
                      <label for="connect-business-monthly">$135/mth Business Plan(unlimited users)</label>
                    </p>
                  </div>

                  <div id="annual-pricing">
                    <p>
                      <input class="with-gap" name="group1" type="radio" id="connect-basic-yearly" value="connect-basic-yearly"/>
                      <label for="connect-basic-yearly">$228/yr Individual Plan(1 user)</label>
                    </p>
                    <p>
                      <input class="with-gap" name="group1" type="radio" id="connect-team-yearly" value="connect-team-yearly"/>
                      <label for="connect-team-yearly">$468/yr Team Plan(5 users)</label>
                    </p>
                    <p>
                      <input class="with-gap" name="group1" type="radio" id="connect-business-yearly" value="connect-business-yearly" />
                      <label for="connect-business-yearly">$1188/yr Business Plan(unlimited users)</label>
                    </p>
                  </div>
                </div>
                <div class="card-content">
                  <p class="debit-explanation">
                    Card Info
                  </p>
                  <span class="payment-errors"></span>
                  <div class="row">
                    <div class="input-field col s12 m12 l12">
                      <input class="ccInput cc-num" type="tel" size="20" placeholder="&#8226;&#8226;&#8226;&#8226;  &#8226;&#8226;&#8226;&#8226;  &#8226;&#8226;&#8226;&#8226;  &#8226;&#8226;&#8226;&#8226;" autocompletetype="cc-number" data-stripe="number">
                      <span class="card-icon" aria-hidden="true"></span>
                      <label>
                        Card Number
                      </label>
                    </div>
                  </div>

                  <div class="row">
                    <div class="input-field col s6 m6 l6">
                      <input class="ccInput cc-exp" type="tel" size="2" placeholder="MM/YY" autocompletetype="cc-exp" data-stripe="exp">
                      <label>
                        Expiration
                      </label>
                    </div>
                    <div class="input-field col s6 m6 l6">
                      <input class="ccInput cc-cvc" type="tel" size="4" placeholder="&#8226;&#8226;&#8226;" autocomplete="off" data-stripe="cvc">
                      <label>
                        CVC
                      </label>
                    </div>
                  </div>

                  <%# TODO: Change this currency to be a select as I add more countries %>
                  <input type="hidden" value="usd" data-stripe="currency">
                  <input id="hidden-plan-id" type="hidden" name="plan" value="<%= @plan %>">

                </div>
                <div class="card-action edit-profile-actions">
                  <input type="submit" class="submit btn waves-effect waves-light" value="Save Subscription">
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

<script>


  console.log("<%= @plan %>")

  <% case @plan %>
  <% when "connect-basic-monthly" %>
    $('#annual-pricing').hide()
    $('#connect-basic-monthly').attr('checked', true);
  <% when "connect-team-monthly" %>
    $('#annual-pricing').hide()
    $('#connect-team-monthly').attr('checked', true);
  <% when "connect-business-monthly" %>
    $('#annual-pricing').hide()
    $('#connect-business-monthly').attr('checked', true);
  <% when "connect-basic-yearly" %>
    $('#monthly-pricing').hide()
    $('#connect-basic-yearly').attr('checked', true);
    $('#pricing_frequency').attr('checked', true);
  <% when "connect-team-yearly" %>
    $('#monthly-pricing').hide()
    $('#connect-team-yearly').attr('checked', true);
    $('#pricing_frequency').attr('checked', true);
  <% when "connect-business-yearly" %>
    $('#monthly-pricing').hide()
    $('#connect-business-yearly').attr('checked', true);
    $('#pricing_frequency').attr('checked', true);
  <% else %>
    $('#annual-pricing').hide()
    $('#hidden-plan-id').val("free")
  <% end %>


  $('#pricing-frequency').change(function () {

    if ($('#pricing_frequency').is(':checked')) {
      $('#monthly-pricing').hide()
      $('#annual-pricing').show()
    } else {
      $('#monthly-pricing').show()
      $('#annual-pricing').hide()
    }
  });

  $('#payment-form input[type=radio]').on('change', function() {
    $('#hidden-plan-id').val($('#payment-form input[type=radio]:checked').val())
  });

  Stripe.setPublishableKey("<%= ENV['stripe_publishable_key'] %>");
  $('input.cc-num').payment('formatCardNumber');
  $('input.cc-exp').payment('formatCardExpiry');
  $('input.cc-cvc').payment('formatCardCVC');

  var validateDetails = function() {

    var expiry = $('.cc-exp').payment('cardExpiryVal');
    var validateExpiry = $.payment.validateCardExpiry(expiry["month"], expiry["year"]);
    var validateCVC = $.payment.validateCardCVC($('.cc-cvc').val());

    if (validateExpiry) {
      $('.cc-exp').addClass('identified');
      $('.cc-exp').addClass('valid');
    } else {
      $('.cc-exp').removeClass('identified');
      $('.cc-exp').removeClass('valid');
    }

    if (validateCVC) {
      $('.cc-cvc').addClass('identified');
      $('.cc-cvc').addClass('valid');
    } else {
      $('.cc-cvc').removeClass('identified');
      $('.cc-cvc').removeClass('valid');
    }


    if (Stripe.validateCardNumber($('input.cc-num').val())) {
      $('.cc-num').addClass("valid");
      $('.cc-num').removeClass("invalid");
    } else {
      $('.cc-num').removeClass("valid");
      $('.cc-num').addClass("invalid");
    }

  }

  $('.ccInput').bind('change paste keyup', function() {
    validateDetails();
  });

  $(function() {
    var $form = $('#payment-form');

    $form.submit(function(event) {
      // Disable the submit button to prevent repeated clicks:
      $form.find('.submit').prop('disabled', true);
      $('')

      $('#payment-form input[type=radio]').on('change', function() {
        console.log($('#payment-form input[type=radio]:checked').val())
         alert($('#payment-form input[type=radio]:checked').val());
      });

      // Request a token from Stripe:
      Stripe.card.createToken($form, stripeResponseHandler);

      // Prevent the form from being submitted:
      return false;
    });
  });

  function stripeResponseHandler(status, response) {
    // Grab the form:
    var $form = $('#payment-form');

    if (response.error) { // Problem!

      // Show the errors on the form:
      $form.find('.payment-errors').show();
      $form.find('.payment-errors').text(response.error.message);
      $form.find('.submit').prop('disabled', false); // Re-enable submission

    } else { // Token was created!

      // Get the token ID:
      var token = response.id;
      // Insert the token ID into the form so it gets submitted to the server:
      $form.append($('<input type="hidden" name="stripeToken">').val(token));

      // Submit the form:
      $form.get(0).submit();
    }
  };

</script>

app/views/profiles/edit.html.erb
<% if @team != nil %>
  <% bg_color = @team.color %>
<% else %>
  <% bg_color = "#FFFFFF" %>
  <% secondary_color = "#f6f6f6" %>
<% end %>

<div class="profile-page">
  <div class="profile-card card">
  <%= form_for(@profile, url: profile_path, method: :put) do |f| %>
    <div class="mdl-card__title mdl-card--expand">
      <div class="profile-header">
        <%= f.label :avatar  do %>
          <% if @person.avatar.length > 1 then %>
            <div class="profile-avatar">
              <div class="section__circle--big large-avatar editable">
                  <img id="avatar" src="<%= @person.avatar %>">
                  <div class="change-label">Change</div>
              </div>
            </div>
          <% else %>
            <div class="profile-avatar">
              <div class="section__circle--big large-avatar editable">
                  <%= image_tag "anonymous_material.png", id: "avatar" %>
                  <div class="change-label">Change</div>
              </div>
            </div>
          <% end %>
        <% end %>
        <%= f.file_field :avatar, style: "display: none;", class: 'photo_upload', onchange: "loadFile(event)" %>

        <div class="guts--narrow__centered">

          <div class="input-field col s12">
            <%= f.text_field :first_name, class: "mdl-textfield__input" %>
            <%= f.label :first_name, class: "mdl-textfield__label" %>
          </div>

          <div class="input-field col s12">
            <%= f.text_field :last_name, class: "mdl-textfield__input" %>
            <%= f.label :last_name, class: "mdl-textfield__label" %>
          </div>

          <div class="input-field col s12">
            <%= f.email_field :email, class: "mdl-textfield__input" %>
            <%= f.label :email, class: "mdl-textfield__label" %>
          </div>

          <div class="input-field col s12">
            <%= f.text_field :phone, class: "mdl-textfield__input" %>
            <%= f.label :phone, class: "mdl-textfield__label" %>
          </div>

        </div>
      </div>
    </div>
    <div class="edit-profile-actions card-action">
      <%= button_tag(type: 'submit', class: "btn waves-effect waves-light") do %>
        Save
      <% end %>
    </div>
  <% end %>
  </div>
</div>

app/views/profiles/show.html.erb
<% if @team != nil %>
  <% bg_color = @team.color %>
<% else %>
  <% bg_color = "#FFFFFF" %>
  <% secondary_color = "#f6f6f6" %>
<% end %>

<div class="profile-page">
  <div class="profile-card card">
    <div class="mdl-card__title mdl-card--expand">
      <div class="profile-header">
        <% if @person.avatar.length > 1 then %>
          <div class="profile-avatar">
            <div class="section__circle--big large-avatar">
                <img src="<%= @person.avatar %>">
            </div>
          </div>
        <% else %>
          <div class="profile-avatar">
            <div class="section__circle--big large-avatar">
                <%= image_tag "anonymous_material.png", id: "avatar" %>
            </div>
          </div>
        <% end %>
        <div class="profile-name">
          <h3><%= @person.first_name %> <%= @person.last_name %></h3>
        </div>
      </div>
    </div>
    <div class="profile-actions card-action">
      <%= link_to "mailto:#{@person.email}", class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect", remote: :true do %>
      Email
      <% end %>
      <% if @team != nil %>
        <%= link_to leave_team_path(:team => @team), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect", data: {confirm: "Are you sure you want to remove #{@person.first_name} from #{@team.name}?"} do %>
         Remove From Team
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/toggle.js.erb
$("#default_properties_container").html("<%= escape_javascript(render partial: 'contact_properties/default_property_rows' ) %>");

app/views/profiles/update.js.erb
$("#payment_details_container").html("<%= escape_javascript(render partial: 'payment_details', locals: { person: @person } ) %>");