config/routes.rb
Rails.application.routes.draw do

  #api
  namespace :api do
    namespace :v1 do
      resources :contacts, only: [:index, :create, :show, :update]
      resources :contact_properties, only: [:index, :create, :show, :update]
      resources :submissions, only: [:index, :create, :show, :update]
      resources :reminders, only: [:index, :create, :show, :update]

      post 'hooks', to: 'hooks#subscribe', as: :hook_subscribe
      delete 'hooks', to: 'hooks#unsubscribe', as: :hook_unsubscribe

    end
  end

  resources :email_templates
  resources :contact_properties
  resources :reminders
  resources :notes
  get 'contacts/batch', to: 'contacts#batch', as: :contacts_batch
  post 'contacts/batch', to: 'contacts#batch_create', as: :contacts_batch_create
  get 'contacts/new_email', to: 'contacts#new_email', as: :contact_new_email
  get 'contacts/draft_list_email', to: 'contacts#draft_list_email', as: :draft_list_email
  post 'contacts/new_email_with_list', to: 'contacts#new_email_with_list', as: :post_contact_new_email
  post 'contact_email', to: 'contacts#send_email', as: :contact_email
  post 'filter_contacts', to: 'contacts#filter', as: :filter_contacts

  resources :submissions
  # get 'submissions', to: 'submissions#index', as: :submissions

  resources :contacts

  get 'transactions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :people,
    path: '',
    path_names:
    {
      sign_up: 'register',
    },
    controllers: {
      registrations: 'people/registrations',
      omniauth_callbacks: "people/omniauth_callbacks"
    }

  resources :invites
  get 'invites/:id/resend', to: 'invites#resend', as: :resend_invite

  resources :profiles
  get 'profiles/:id/leave', to: 'profiles#leave', as: :leave_team
  get 'profiles/:id/account', to: 'profiles#account', as: :account
  post 'profiles/:id/toggle', to: 'profiles#toggle', as: :toggle


  get 'admins/new', to: 'admins#new', as: :new_admin
  post 'admins', to: 'admins#create', as: :create_admin

  resources :orgs
  # resources :orgs, :path => ''
  # # resources :orgs, :path => '', :only => [] do
  # #   resources :projects, :path => '', :except => [:index]
  # # end


  resources :transactions, only: [:new, :create]

  post 'connect_subscribe', to: 'transactions#connect_subscribe', as: :connect_payment
  post 'update_subscription', to: 'transactions#update_subscription', as: :update_subscription

  get 'inbox', to: 'inbox#all', as: :inbox


  post "/webhooks", to: 'webhooks#recieve'

  get '/onboarding', to: 'relate_onboarding#profile'
  put '/onboarding', to: 'relate_onboarding#update_profile'

  resources :onboarding


  get '/tos', to: 'marketing#tos'

  get '/', to: 'marketing#relate', as: :home
  get "/", to: 'marketing#relate', as: :onside_home
  root to: 'marketing#relate'


end

app/controllers/inbox_controller.rb
class InboxController < ApplicationController
  layout "relate"

  before_action :authenticate_person!
  before_action :active_org, :set_current_person_tasks, :set_unassigned_tasks, :set_new_submissions, :get_due_tasks

  def all
    # @new_submissions = @active_org.submissions.where(status: "new").order('updated_at DESC')
    @approved_submissions = @active_org.submissions.where(status: "approved").order('updated_at DESC')
    @rejected_submissions = @active_org.submissions.where(status: "rejected").order('updated_at DESC')
    @maybe_submissions = @active_org.submissions.where(status: "maybe").order('updated_at DESC')

    @contacts = @active_org.contacts

    items = @current_person_tasks + @unassigned_tasks + @new_submissions + @approved_submissions + @rejected_submissions + @maybe_submissions

    @inbox_items = items.sort!{|b,a| a.created_at <=> b.created_at}

    @reminders = Reminder.all

  end

end

app/views/inbox/_inbox_item.html.erb
<% if item.class == Submission %>
  Submission
<% elsif item.class == Reminder %>
  <% unless item.status == "archived" %>
    <div class="task-line">
      <% if item.status == "complete" %>
        <div class="task-check-label">
          <%= link_to reminder_path(item, item: {status: "incomplete"}), method: :put, remote: true do %>
            <input type="checkbox" checked id="<%= item.id %>_check" />
            <label class="" style="color: rgba(0, 0, 0, 0.87059);" data-position="bottom" data-delay="50" data-tooltip="<%= item.label %>" for="<%= item.id %>_check">
                <del>
                  <% if truncate_length > 49 && item.contact && item.contact %>
                    <strong><%= item.contact.first_name[0] %>. <%= item.contact.last_name %></strong>:
                  <% end %>
                  <%= item.label.truncate(truncate_length) %>
                </del>
            </label>
          <% end %>
        </div>
      <% elsif item.status == "incomplete" %>
        <div class="task-check-label">
          <%= link_to reminder_path(item, item: {status: "complete"}), method: :put, remote: true do %>
            <input type="checkbox" id="<%= item.id %>_check" />
            <label class="" style="color: rgba(0, 0, 0, 0.87059);" data-position="bottom" data-delay="50" data-tooltip="<%= item.label %>" for="<%= item.id %>_check">
              <% if truncate_length > 49 && item.contact %>
                <strong><%= item.contact.first_name[0] %>. <%= item.contact.last_name %></strong>:
              <% end %>
              <%= item.label.truncate(truncate_length) %>
            </label>
          <% end %>
        </div>
      <% end %>
      <div class="task-due-edit">
        <div class="date">
          <% if item.next_date && item.next_date == Date.tomorrow %>
             <div class="chip" style="background-color: rgba(0,0,255,0.25);;">
               Tomorrow
             </div>
          <% elsif item.next_date && item.next_date == Date.today %>
            <div class="chip" style="background-color: rgba(0,128,0,0.3);">
               Today
            </div>
          <% elsif item.next_date && item.next_date > Date.today %>
            <%= item.next_date.strftime("%b %e")%>
          <% elsif item.next_date && item.next_date < Date.today %>
            <div class="chip" style="background-color: rgba(255, 88, 58, 0.34);">
              <%= item.next_date.strftime("%b %e")%>
            </div>
          <% else %>
          <% end %>

          <!-- <%= item.next_date.strftime("%b #{item.next_date.day.ordinalize}") %> -->
        </div>
        <div>
          <%= link_to edit_reminder_path(item) do %>
            <i class="material-icons" style="display: inline;">mode_edit</i>
          <% end %>
        </div>
        <% if item.status == "complete" %>
          <div>
            <%= link_to reminder_path(item, item: {status: "archived"}), method: :put, remote: true do %>
              <i class="material-icons" style="display: inline;">archive</i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="card-content">
    Unknown Activity
  </div>
<% end %>

app/views/inbox/_inbox_item_list.html.erb
<% inbox_items.each do |item| %>
  <%= render 'inbox_item', item: item, truncate_length: 49 %>
<% end %>

app/views/inbox/all.html.erb
<div class="row" style="background: #ffffff;">
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s3"><a class="active" href="#all">All</a></li>
      <li class="tab col s3"><a class="active" href="#my-tasks">My Tasks</a></li>
      <li class="tab col s3"><a class="active" href="#submissions">Submissions</a></li>
      <li class="tab col s3"><a href="#unassigned">Unassigned</a></li>
    </ul>
  </div>
</div>

<div class="container">

  <div id="all" class="col s12">
    <div class="card team-card">
      <div class="card-content">
        <div id="all_items_container">
            <%= render 'inbox_item_list', inbox_items: @inbox_items %>
        </div>
      </div>
    </div>
  </div>

  <div id="my-tasks" class="col s12">
    <div class="card team-card">
      <div class="card-content">
        <div id="cp_task_list_container">

          <% if @current_person_tasks.length == 0 %>
            <div style="width: 100%; text-align: center;">Good work. <br>You have no outstanding tasks. </div>
          <% else %>
            <%= render 'contacts/task_list', reminders: @current_person_tasks, truncate_length: 50 %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div id="submissions" class="col s12">
    <div class="card team-card">
      <div class="card-content">
        <div id="new-submission-list-container" class="container">
          <%= render 'submissions/new_submissions', new_submissions: @new_submissions %>
        </div>
      </div>
    </div>
  </div>


  <div id="unassigned" class="col s12" style="position: relative;">

    <div class="card team-card">
      <div class="card-content">
        <div id="ua_task_list_container">

          <% if @unassigned_tasks.length == 0 %>
            <div style="width: 100%; text-align: center;">No unassigned tasks. </div>
          <% else %>
            <%= render 'contacts/task_list', reminders: @unassigned_tasks, truncate_length: 50 %>
          <% end %>

        </div>
      </div>
    </div>

  </div>
</div>

<div class="fixed-action-btn">
  <a class="btn-floating btn-large">
    <i class="large material-icons">add</i>
  </a>
  <ul>
    <li><a class="btn-floating tooltipped" data-position="left" data-delay="70" data-tooltip="Contact" href="<%= new_contact_path %>"><i class="material-icons">person_add</i></a></li>
    <li><a class="btn-floating tooltipped" data-position="left" data-delay="70" data-tooltip="Task" href="<%= new_reminder_path %>"><i class="material-icons">check_box</i></a></li>
    <li><a class="btn-floating tooltipped" data-position="left" data-delay="70" data-tooltip="Email" href="<%= contact_new_email_path %>"><i class="material-icons">mail_outline</i></a></li>
    <li><a class="btn-floating tooltipped" data-position="left" data-delay="70" data-tooltip="Note" href="<%= new_note_path %>"><i class="material-icons">note_add</i></a></li>
  </ul>
</div>