config/routes.rb
Rails.application.routes.draw do

  #api
  namespace :api do
    namespace :v1 do
      resources :contacts, only: [:index, :create, :show, :update]
      resources :contact_properties, only: [:index, :create, :show, :update]
      resources :submissions, only: [:index, :create, :show, :update]
      resources :reminders, only: [:index, :create, :show, :update]

      post 'hooks', to: 'hooks#subscribe', as: :hook_subscribe
      delete 'hooks', to: 'hooks#unsubscribe', as: :hook_unsubscribe

    end
  end

  resources :email_templates
  resources :contact_properties
  resources :reminders
  resources :notes
  get 'contacts/batch', to: 'contacts#batch', as: :contacts_batch
  post 'contacts/batch', to: 'contacts#batch_create', as: :contacts_batch_create
  get 'contacts/new_email', to: 'contacts#new_email', as: :contact_new_email
  get 'contacts/draft_list_email', to: 'contacts#draft_list_email', as: :draft_list_email
  post 'contacts/new_email_with_list', to: 'contacts#new_email_with_list', as: :post_contact_new_email
  post 'contact_email', to: 'contacts#send_email', as: :contact_email
  post 'filter_contacts', to: 'contacts#filter', as: :filter_contacts

  resources :submissions
  # get 'submissions', to: 'submissions#index', as: :submissions

  resources :contacts

  get 'transactions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :people,
    path: '',
    path_names:
    {
      sign_up: 'register',
    },
    controllers: {
      registrations: 'people/registrations',
      omniauth_callbacks: "people/omniauth_callbacks"
    }

  resources :invites
  get 'invites/:id/resend', to: 'invites#resend', as: :resend_invite

  resources :profiles
  get 'profiles/:id/leave', to: 'profiles#leave', as: :leave_team
  get 'profiles/:id/account', to: 'profiles#account', as: :account
  post 'profiles/:id/toggle', to: 'profiles#toggle', as: :toggle


  get 'admins/new', to: 'admins#new', as: :new_admin
  post 'admins', to: 'admins#create', as: :create_admin

  resources :orgs
  # resources :orgs, :path => ''
  # # resources :orgs, :path => '', :only => [] do
  # #   resources :projects, :path => '', :except => [:index]
  # # end


  resources :transactions, only: [:new, :create]

  post 'connect_subscribe', to: 'transactions#connect_subscribe', as: :connect_payment
  post 'update_subscription', to: 'transactions#update_subscription', as: :update_subscription

  get 'inbox', to: 'inbox#all', as: :inbox


  post "/webhooks", to: 'webhooks#recieve'

  get '/onboarding', to: 'relate_onboarding#profile'
  put '/onboarding', to: 'relate_onboarding#update_profile'

  resources :onboarding


  get '/tos', to: 'marketing#tos'

  get '/', to: 'marketing#relate', as: :home
  get "/", to: 'marketing#relate', as: :onside_home
  root to: 'marketing#relate'


end

app/controllers/marketing_controller.rb
class MarketingController < ApplicationController
  def home
  end

  def tos
  end

  def software
  end

  def harrisburg
    @orgs = [
      {
        name: "Harrisburg Area Co-ed Pickup",
        external_link: "https://www.facebook.com/groups/437756026254931/",
        category: "Pickup",
        opps: [
          {
            name: "Friday Night Indoor Pickup",
            timeframe: "Friday Night",
            in_or_outdoor: "Indoor",
            category: "Pickup",
            price: "$7",
            external_link: "http://www.meetup.com/Harrisburg-Area-Co-ed-Pick-up-Soccer/",
            basics: [
              "Adult - Open",
              "Coed",
              "Pickup",
              "Indoor"
            ],
            next_start: {
              date: "November 11th",
              time: "9pm ET"
            },
            location: {
              name: "Yellow Breeches Sports Center",
              location_link: "http://yellowbreechessports.com/",
              address: {
                street: "700 Shawnee Court",
                city: "New Cumberland",
                state: "PA",
                zip: "17070"
              },
              address_link: "https://goo.gl/maps/2QabFnC3d7S2"
            }
          },
          {
            name: "Saturday Morning Pickup",
            timeframe: "Saturday Morning",
            in_or_outdoor: "Outdoor",
            category: "Pickup",
            price: "FREE",
            external_link: "https://www.facebook.com/events/609921559192439/",
            basics: [
              "Adult - Open",
              "Coed",
              "Pickup",
              "Outdoor"
            ],
            next_start: {
              date: "November 12th",
              time: "10:15am ET"
            },
            location: {
              name: "Sporting Hill Elementary School",
              location_link: "#",
              address: {
                street: "210 S Sporting Hill Rd",
                city: "Mechanicsburg",
                state: "PA",
                zip: "17050"
              },
              address_link: "https://goo.gl/maps/4juzkqApgQx"
            }
            # location: {
            #   name: "Adams Ricci Park",
            #   location_link: "#",
            #   address: {
            #     street: "100 E Penn Dr",
            #     city: "Enola",
            #     state: "PA",
            #     zip: "17025"
            #   },
            #   address_link: "https://goo.gl/maps/XZSZayxBfbU2"
            # }
          }
        ]
      },
      {
        name: "Twin Ponds",
        external_link: "http://twinponds.com/soccer/",
        category: "Facility",
        opps: [
          {
            name: "Monday Night Indoor Pickup",
            timeframe: "Monday Night",
            in_or_outdoor: "Indoor",
            category: "Pickup",
            price: "$5",
            external_link: "http://twinponds.com/soccer/open-soccer/",
            basics: [
              "Adult - 16+",
              "Coed",
              "Pickup",
              "Indoor"
            ],
            next_start: {
              date: "November 7th",
              time: "9pm ET"
            },
            location: {
              name: "Twin Ponds West",
              location_link: "http://twinponds.com/soccer/",
              address: {
                street: "200 Lambs Gap Road",
                city: "Mechanicsburg",
                state: "PA",
                zip: "17050"
              },
              address_link: "https://goo.gl/maps/guQsjxiq9LR2"
            }
          },
          {
            name: "Wednesday Night Indoor Pickup",
            timeframe: "Wednesday Night",
            in_or_outdoor: "Indoor",
            category: "Pickup",
            price: "$5",
            external_link: "http://twinponds.com/soccer/open-soccer/",
            basics: [
              "Adult - 16+",
              "Coed",
              "Pickup",
              "Indoor"
            ],
            next_start: {
              date: "November 9th",
              time: "9pm ET"
            },
            location: {
              name: "Twin Ponds West",
              location_link: "http://twinponds.com/soccer/",
              address: {
                street: "200 Lambs Gap Road",
                city: "Mechanicsburg",
                state: "PA",
                zip: "17050"
              },
              address_link: "https://goo.gl/maps/guQsjxiq9LR2"
            }
          },
          {
            name: "Men's Over 30",
            timeframe: "Monday Night",
            in_or_outdoor: "Indoor",
            category: "League",
            price: "TBD",
            external_link: "http://twinponds.com/soccer/adult-soccer/",
            basics: [
              "Over 30",
              "Men",
              "Season",
              "Indoor"
            ],
            next_start: {
              date: "TBD",
              time: "TBD"
            },
            location: {
              name: "Twin Ponds West",
              location_link: "http://twinponds.com/soccer/",
              address: {
                street: "200 Lambs Gap Road",
                city: "Mechanicsburg",
                state: "PA",
                zip: "17050"
              },
              address_link: "https://goo.gl/maps/guQsjxiq9LR2"
            }
          },
          {
            name: "Women's Over 30",
            timeframe: "Friday Night",
            in_or_outdoor: "Indoor",
            category: "League",
            price: "TBD",
            external_link: "http://twinponds.com/soccer/adult-soccer/",
            basics: [
              "Over 30",
              "Women",
              "Season",
              "Indoor"
            ],
            next_start: {
              date: "TBD",
              time: "TBD"
            },
            location: {
              name: "Twin Ponds West",
              location_link: "http://twinponds.com/soccer/",
              address: {
                street: "200 Lambs Gap Road",
                city: "Mechanicsburg",
                state: "PA",
                zip: "17050"
              },
              address_link: "https://goo.gl/maps/guQsjxiq9LR2"
            }
          },
        ]
      },
      {
        name: "Harrisburg City Islanders",
        external_link: "http://cityislanders.com/",
        category: "Club",
        opps: [
          {
            name: "Pro Tryout",
            timeframe: "Tuesday and Wednesday Morning and Afternoon",
            in_or_outdoor: "Indoor",
            category: "Tryout",
            price: "$100",
            external_link: "http://cityislanders.com/press-releases/harrisburg-city-islanders-announce-pro-team-tryout/",
            basics: [
              "Pro",
              "Tryout"
            ],
            next_start: {
              date: "November 22th",
              time: "9am ET"
            },
            location: {
              name: "In The Net",
              location_link: "http://www.inthenet.com/",
              address: {
                street: "798 Airport Road",
                city: "Palmyra",
                state: "PA",
                zip: "17078"
              },
              address_link: "https://goo.gl/maps/q8oEaJzjTYC2"
            }
          }
        ]
      },
      {
        name: "Yellow Breeches Sports Center",
        external_link: "http://yellowbreechessports.com/sports/soccer/",
        category: "Facility",
        opps: [
          {
            name: "Tuesday Men's Indoor",
            timeframe: "Tuesday Nights",
            in_or_outdoor: "Indoor",
            category: "Season",
            price: "$35",
            external_link: "http://yellowbreechessports.com/docs/soccer/ADULT-SOCCER-LEAGUE-Winter-1-2016.pdf",
            basics: [
              "Season",
              "Indoor",
              "Men's - Open",
            ],
            next_start: {
              date: "November 8th",
              time: "9pm ET"
            },
            location: {
              name: "Yellow Breeches Sports Center",
              location_link: "http://yellowbreechessports.com/",
              address: {
                street: "700 Shawnee Court",
                city: "New Cumberland",
                state: "PA",
                zip: "17070"
              },
              address_link: "https://goo.gl/maps/2QabFnC3d7S2"
            }
          },
          {
            name: "Thursday Men's Indoor",
            timeframe: "Thursdays Nights",
            in_or_outdoor: "Indoor",
            category: "Season",
            price: "$35",
            external_link: "http://yellowbreechessports.com/docs/soccer/ADULT-SOCCER-LEAGUE-Winter-1-2016.pdf",
            basics: [
              "Season",
              "Indoor",
              "Men's - Open",
            ],
            next_start: {
              date: "November 10th",
              time: "9pm ET"
            },
            location: {
              name: "Yellow Breeches Sports Center",
              location_link: "http://yellowbreechessports.com/",
              address: {
                street: "700 Shawnee Court",
                city: "New Cumberland",
                state: "PA",
                zip: "17070"
              },
              address_link: "https://goo.gl/maps/2QabFnC3d7S2"
            }
          },
          {
            name: "Monday Coed Indoor",
            timeframe: "Monday Nights",
            in_or_outdoor: "Indoor",
            category: "Season",
            price: "$35",
            external_link: "http://yellowbreechessports.com/docs/soccer/ADULT-SOCCER-LEAGUE-Winter-1-2016.pdf",
            basics: [
              "Season",
              "Indoor",
              "Adult - Open",
              "Coed",
            ],
            next_start: {
              date: "November 7th",
              time: "9pm ET"
            },
            location: {

app/views/marketing/_connect_header.html.erb
<nav id="connect-header" class="marketing">
  <div class="nav-wrapper">
     <a title="Home to Onside Harrisburg" href="/" class="brand-logo">
       <div class="logo-container">
         <%= image_tag "onside-horizontal-white.svg", class: "header-logo" %>
       </div>
     </a>
     <a id="register-side-menu-icon" href="#" data-activates="connect-side-menu" class="button-collapse"><i class="material-icons" style="color: white;">menu</i></a>
     <ul class="right hide-on-med-and-down">
       <!-- <li><a href="#demo">Demo</a></li>
       <li><a href="#features">Features</a></li>
       <li><a href="#pricing">Pricing</a></li> -->
       <!-- <li><a href="http://playonside.com">About</a></li> -->
       <li><a id="mainNavPricing" href="#pricing">Pricing</a></li>
       <li><a href="<%= new_person_session_path %>">Sign In</a></li>
       <li>
         <%= link_to "Start Free Trial", new_person_registration_path(plan: "free"), class: "btn blue white-text waves-effect waves-blue" %>
       </li>
     </ul>
     <ul class="side-nav" id="connect-side-menu">
       <!-- <li><a href="#demo">Demo</a></li>
       <li><a href="#features">Features</a></li>
       <li><a href="#pricing">Pricing</a></li> -->
       <!-- <li><a href="http://playonside.com">About</a></li> -->
       <li><a href="<%= new_person_session_path %>" style="color: #424242;">Sign In</a></li>
       <li>
          <%= link_to "Start Free Trial", new_person_registration_path(plan: "free"), class: "btn blue white-text waves-effect waves-blue" %>
       </li>
     </ul>
  </div>
</nav>

app/views/marketing/tos.html.erb
<div class="mini-header"></div>
<div class="container">
  <div class="card">
    <div class="card-content">
      <div class="card-title">
        <h2>Onside Terms of Service and Privacy Policy</h2>
      </div>



      <h3>1. Terms</h3>

        <p>By accessing the website at&nbsp;<a href="http://playonside.com">http://playonside.com</a>, you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law.</p>

      <h3>2. Use License</h3>

        <ol type="a">
          <li>
            Permission is granted to temporarily download one copy of the materials (information or software) on Onside's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:

            <ol type="i">
              <li>modify or copy the materials;</li>
              <li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
              <li>attempt to decompile or reverse engineer any software contained on Onside's website;</li>
              <li>remove any copyright or other proprietary notations from the materials; or</li>
              <li>transfer the materials to another person or "mirror" the materials on any other server.</li>
            </ol>
          </li>
          <li>This license shall automatically terminate if you violate any of these restrictions and may be terminated by Onside at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.</li>
        </ol>

      <h3>3. Disclaimer</h3>

        <ol type="a">
          <li>The materials on Onside's website are provided on an 'as is' basis. Onside makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</li>
          <li>Further, Onside does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.</li>
        </ol>

      <h3>4. Limitations</h3>

        <p>In no event shall Onside or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Onside's website, even if Onside or a Onside authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.</p>

      <h3>5. Accuracy of materials</h3>

        <p>The materials appearing on Onside's website could include technical, typographical, or photographic errors. Onside does not warrant that any of the materials on its website are accurate, complete or current. Onside may make changes to the materials contained on its website at any time without notice. However Onside does not make any commitment to update the materials.</p>

      <h3>6. Links</h3>

        <p>Onside has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Onside of the site. Use of any such linked website is at the user's own risk.</p>

      <h3>7. Modifications</h3>

        <p>Onside may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.</p>

      <h3>8. Governing Law</h3>

        <p>These terms and conditions are governed by and construed in accordance with the laws of Pennsylvania and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.</p>

      <h3>9. Payment Processing</h3>
        Payment processing services for league and team treasurers on Onside are provided by Stripe and are subject to the <a href="https://stripe.com/us/connect-account/legal">Stripe Connected Account Agreement</a>, which includes the Stripe Terms of Service (collectively, the “Stripe Services Agreement”). By agreeing to these terms or continuing to operate as a treasurer on Onside, you agree to be bound by the Stripe Services Agreement, as the same may be modified by Stripe from time to time. As a condition of Onside enabling payment processing services through Stripe, you agree to provide Onside accurate and complete information about you and your business, and you authorize Onside to share it and transaction information related to your use of the payment processing services provided by Stripe.

      <h2>Privacy Policy</h2>

        <p>Your privacy is important to us.</p>

        <p>It is Onside's policy to respect your privacy regarding any information we may collect while operating our website. Accordingly, we have developed this privacy policy in order for you to understand how we collect, use, communicate, disclose and otherwise make use of personal information. We have outlined our privacy policy below.</p>

        <ul>
          <li>We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned.</li>
          <li>Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.</li>
          <li>We will collect and use personal information solely for fulfilling those purposes specified by us and for other ancillary purposes, unless we obtain the consent of the individual concerned or as required by law.</li>
          <li>Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date.</li>
          <li>We will protect personal information by using reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.</li>
          <li>We will make readily available to customers information about our policies and practices relating to the management of personal information.</li>
          <li>We will only retain personal information for as long as necessary for the fulfilment of those purposes.</li>
        </ul>

        <p>We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained. Onside may change this privacy policy from time to time at Onside's sole discretion.</p>


    </div>
  </div>
</div>